# Generated by Django 2.2 on 2019-04-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0004_auto_20190423_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='department_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='hall_name',
            field=models.CharField(blank=True, default='Dr. muhammad sahidullah hall', max_length=100, null=True),
        ),
    ]
