# Generated by Django 2.2 on 2019-04-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0005_auto_20190423_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='admission_year',
            field=models.PositiveIntegerField(blank=True, default=1980, null=True),
        ),
    ]
