# Generated by Django 2.2 on 2019-04-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0007_userprofileinfo_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
