# Generated by Django 2.2 on 2019-04-23 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0009_userprofileinfo_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
    ]
