# Generated by Django 2.2 on 2019-04-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0010_remove_userprofileinfo_portfolio_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='profile_pic',
        ),
    ]
